// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection: Prisma Migrate takes
    // a session-level advisory lock, which connection poolers like Neon's
    // (or PgBouncer in transaction mode) don't support and will time out on.
    // The app itself still uses the pooled DATABASE_URL at runtime (see
    // src/lib/prisma.ts) — only the CLI's migration step uses this one.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
